DROP TABLE IF EXISTS ITEM CASCADE;

CREATE TABLE ITEM(
 ID INT NOT NULL PRIMARY KEY,
 ITEM_NAME VARCHAR(100),
 PRICE INT,
 GROUPID VARCHAR(6),
 REGIST_DATE DATE,
 VERSION_NO INT
);

DROP TABLE IF EXISTS USER_INFO CASCADE;

CREATE TABLE USER_INFO(
 USERNAME VARCHAR(100) NOT NULL PRIMARY KEY,
 ROLES VARCHAR(100),
 PASSWORD VARCHAR(100),
 EMAIL VARCHAR(100),
 REGIST_DATE DATE,
 VERSION_NO INT
);